# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7"  # 3.7 development branch
  - "3.8"  # 3.8 development branch
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
# command to run tests
script:
  - pytest

matrix:
  include:
    - python: "3.6"
      env: ENV=pytest
    - python: "3.7"
      env: ENV=pytest
    - python: "3.8"
      env: ENV=pytest

    - name: "Mac Build"
      os: osx
      language: generic
      env: ENV=pytest
      before_install:
        - pip install poetry
      install:
        - poetry install
      script:
        - poetry run pytest

    - name: "Python 3.9 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install poetry
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
      script: poetry run pytest